### ISSUE TITLE
Fork, PR or new repo to do up-to-date version?

### ISSUE THREAD

**Issue by mungojam** [nathansamson/xamarin-android-docker#5]
Hi there, thanks so much for putting this up as it got me (very nearly) up and running with an [up to date version](https://github.com/mungojam/docker-xamarin-android-linux/blob/master/Dockerfile) targeting SDK 28.

I started out in my own repo, but now I realise that it would have been more polite to see first if you were happy to take PRs and keep yours up and running since hacking yours was how I made mine and yours currently comes up high in google and DockerHub too.

Let me know if you'd like to try and maintain yours or I'm happy to go with my own and mention yours in the Readme.

As you'll see from my [one issue](https://github.com/mungojam/docker-xamarin-android-linux/issues/1), I think I am stumbling at one final piece of the puzzle. Once that's solved, I'd like to get it up on DockerHub and publicise a bit as there doesn't appear to be any other up-to-date examples on the web.

Note that I started mine based on .net core 3 image but I don't think I'm actually using that SDK at all now, I think it's all mono so I'll probably try and cut that bit out later. Bring on .net 5 when this should be much simpler!

**Comment by mungojam** [comment]
Looks like others got their first with forks. [This one](https://github.com/vonProteus/xamarin-android-docker) looks most promising

**Comment by nathansamson** [comment]
Hi tnaks for your intrest!

Note that this repo was setup for our company, but we never intended it to be fully usable for other people or to do proper maintaining / versioning etc...
On top of that are we also moving away from Xamarin / Android, so the use for this repo (and keeping it up to date) has become zero for us

So I encourage you to create a fork (or use an existing fork), as PR's will stay unanswered
