### ISSUE TITLE
Issue with latest Docker image

### ISSUE THREAD

**Issue by Surbhidhingra** [nathansamson/xamarin-android-docker#6]
Hi, 

I am facing below issue with latest docker image. I am using this for Gitlab. Please let me know how to resolve this. Thanks!

Running with gitlab-runner 11.11.2 (ac2a293c)
  on sandbox fnuTUMb-
Using Docker executor with image nathansamson/xamarin-android-docker:v26.0.2-20180221 ...
Pulling docker image nathansamson/xamarin-android-docker:v26.0.2-20180221 ...
ERROR: Job failed: Error response from daemon: manifest for nathansamson/xamarin-android-docker:v26.0.2-20180221 not found (executor_docker.go:175:0s)

**Comment by nathansamson** [comment]
Not sure why docker hub did not build this version, but note this repo is deprecated.
You are free to use the Dockerfile and build  (and publish) it yourself
